# Site settings
author: Leah Hirschfeld
title: Journey into Software Engineering
header-img: img/home-bg.png
email: leah.hirschfeld@gmail.com
copyright_name: Leah Hirschfeld
description: > # this means to ignore newlines until "baseurl:"
  Short tales of one woman's adventure into software engineering
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  leah-hirschfeld

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
